### ISSUE TITLE
使用Fiddler抓包软件抓不到消灭病毒的数据是怎么回事呢？

### ISSUE THREAD

**Issue by DevXue** [WindrunnerMax/EliminVirus#1]
在Fiddler中查看关键字网址为chiji-h5.com的包，点开没有任何数据··
是我的操作有问题吗？  新手不太懂这个  求指点谢谢。
![img](https://user-images.githubusercontent.com/9455329/60569247-72090500-9da1-11e9-9496-29becc36b9d6.jpg)

**Comment by WindRunnerMax** [comment]
你的Fiddler的HTTPS证书安装好了嘛

**Comment by DevXue** [comment]
安装了，一直能抓Https接口的包，不知道为啥这个游戏不可以···
我用了个5.0的手机装了一个Packet Capture  APP 获取到了openID，  大佬，你的辅助太牛逼了！

**Comment by WindRunnerMax** [comment]
你悠着点玩😏我现在就是毫无游戏体验了😐

**Comment by DevXue** [comment]
哈哈哈哈，   是了么，武器升了之后过于牛B，  现在一点快感也没了···

**Comment by WindRunnerMax** [comment]
😏其实还可以装逼用呢😏其实啥数据都可以改，还可以把武器啥的再改回去😂

**Comment by DevXue** [comment]
太6了，大佬能否分享一下实现这个辅助的原理，我准备学Python呀！  太特么牛逼了。

**Comment by WindRunnerMax** [comment]
原理没啥原理啊，就是抓数据包，修改后提交服务端，比较难得就是那个加密sign,这个得反编译那个小游戏，在gayhub有反编译的工具，然后你还需要一台ROOT的手机，反编译以后看懂他的加密算法就OK。做脚本的确是python方便，但是假如单单用这个脚本来说，用Java,PHP,NODEJS等等任何一种可以发送HTTP请求的语言都是可以做的

**Comment by DevXue** [comment]
嗯嗯，说得对，  有一点我一直没搞明白， 数据抓包我倒是懂，就是怎么把咱们修改后的包提交到对方服务器呢？   还有  修改的过程中 这个原始的数据包是拦截状态？？没有提交过去吗？？还是提交过去了？我们做了修改后再次提交？从而修改了数据。。  这个我一直不太懂！  还请大佬指点迷津！

**Comment by WindRunnerMax** [comment]
有URL了，只要符合对方规范那肯定是能够向服务端提交过去数据的，具体可以学一下爬虫，至于拦截数据包这个脚本肯定不是这样的啊😐拦截数据包是fiddler这种拦截你玩游戏时网络请求的包，这个脚本完全就是模拟了一次正常的请求而已，算是两次吧，第一次是我获取了你现在的游戏数据，第二次是把数据改了提交，就完事了

**Comment by DevXue** [comment]
哈哈！  感谢感谢，我懂了！

**Comment by zhangkangning** [comment]
我也遇到你问的那个问题了，证书都装了，但是没有消灭病毒的任何数据啊，求解啊

**Comment by WindRunnerMax** [comment]
> 我也遇到你问的那个问题了，证书都装了，但是没有消灭病毒的任何数据啊，求解啊

安卓7及以上不信任用户证书了，要么Root把证书升级为系统证书，要么就换个低版本安卓
